apiVersion: v1
kind: Pod
metadata:
  name: minio-test-pod
  namespace: training
spec:
  containers:
    - name: test-container
      image: ubuntu
      command: ["sleep", "3600"]
      volumeMounts:
        - name: s3-volume
          mountPath: /mnt/minio
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: csi-s3-pvc
