apiVersion: v1
kind: Service
metadata:
  name: csi-attacher-glusterfsplugin
  labels:
    app: csi-attacher-glusterfsplugin
spec:
  selector:
    app: csi-attacher-glusterfsplugin
  ports:
    - name: dummy
      port: 12345

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: csi-attacher-glusterfsplugin
spec:
  serviceName: csi-attacher
  replicas: 1
  selector:
    matchLabels:
      app: csi-attacher-glusterfsplugin
  template:
    metadata:
      labels:
        app: csi-attacher-glusterfsplugin
    spec:
      serviceAccountName: glusterfs-csi
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: glusterfs
          image: docker.io/gluster/glusterfs-csi-driver
          args:
            - "--nodeid=$(NODE_ID)"
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--resturl=$(REST_URL)"
            - "--resttimeout=120"
            - "--restsecret=$(REST_SECRET)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: REST_URL
              value: http://192.168.1.20:24007
            - name: REST_SECRET
              value: b03045b7988258557ecd3e136cd37ba3f928ea0831b3b1b7ed8ae238d36d9071
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir: {}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-nodeplugin-glusterfsplugin
spec:
  selector:
    matchLabels:
      app: csi-nodeplugin-glusterfsplugin
  template:
    metadata:
      labels:
        app: csi-nodeplugin-glusterfsplugin
    spec:
      serviceAccountName: glusterfs-csi
      hostNetwork: true
      containers:
        - name: csi-node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/org.gluster.glusterfs /registration/org.gluster.glusterfs-reg.sock"]
          env:
            - name: ADDRESS
              value: /plugin/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins_registry/org.gluster.glusterfs/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: glusterfs
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: docker.io/gluster/glusterfs-csi-driver
          args:
            - "--nodeid=$(NODE_ID)"
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--resturl=$(REST_URL)"
            - "--resttimeout=120"
            - "--restsecret=$(REST_SECRET)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: REST_URL
              value: http://192.168.1.21:24007
            - name: REST_SECRET
              value: b03045b7988258557ecd3e136cd37ba3f928ea0831b3b1b7ed8ae238d36d9071
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/org.gluster.glusterfs
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: csi-provisioner-glusterfsplugin
  labels:
    app: csi-provisioner-glusterfsplugin
spec:
  selector:
    app: csi-provisioner-glusterfsplugin
  ports:
    - name: dummy
      port: 12345

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: csi-provisioner-glusterfsplugin
spec:
  serviceName: csi-provisioner-glusterfsplugin
  replicas: 1
  selector:
    matchLabels:
      app: csi-provisioner-glusterfsplugin
  template:
    metadata:
      labels:
        app: csi-provisioner-glusterfsplugin
    spec:
      serviceAccountName: glusterfs-csi
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--provisioner=org.gluster.glusterfs"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-cluster-driver-registrar
          image: quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
          args:
            - "--v=5"
            - "--pod-info-mount-version=v1"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v1.0.1
          args:
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: glusterfs
          image: docker.io/gluster/glusterfs-csi-driver
          args:
            - "--nodeid=$(NODE_ID)"
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--resturl=$(REST_URL)"
            - "--resttimeout=120"
            - "--restsecret=$(REST_SECRET)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: REST_URL
              value: http://192.168.121.182:24007
            - name: REST_SECRET
              value: b03045b7988258557ecd3e136cd37ba3f928ea0831b3b1b7ed8ae238d36d9071
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: glusterfs-csi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glusterfs-csi
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch", "delete", "get"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glusterfs-csi-role
subjects:
  - kind: ServiceAccount
    name: glusterfs-csi
    namespace: default
roleRef:
  kind: ClusterRole
  name: glusterfs-csi
  apiGroup: rbac.authorization.k8s.io
