apiVersion: v1
kind: Service
metadata:
  name: httpd-lb
  labels:
    app: httpd-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  selector:
    app: httpd-app
  ports:
    - port: 80
      targetPort: 80