apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alice-read-only
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      -
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alice-read-only-binding
subjects:
  - kind: User
    name: alice
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: alice-read-only
  apiGroup: rbac.authorization.k8s.io
