apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-dep
  namespace: training
  annotations:
    kubernetes.io/change-cause: "v2 release"
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
#    matchLabels:
#      app-name: "echo-server"
    matchExpressions:
      - key: app-name
        values:
          - echo-server
          - echo
        operator: In
  template:
    metadata:
      namespace: training
      labels:
        app-name: "echo-server"
        env: "dev"
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server:v2
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "64M"
              cpu: "250m"
            limits:
              memory: "128M"
              cpu: "500m"
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 3
