apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-test-dep
  namespace: training
  annotations:
    kubernetes.io/change-cause: "initial release"
spec:
  replicas: 5
  selector:
    matchLabels:
      app-name: "nginx"
  template:
    metadata:
      namespace: training
      labels:
        app-name: "nginx"
    spec:
      containers:
        - name: nginx
          image: nginx:1.21-alpine
          ports:
            - containerPort: 80
          volumeMounts:
              - name: storage
                mountPath: /usr/share/nginx/html
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc