kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: minio-sc
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  # you can set mount options here, for example limit memory cache size (recommended)
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  # to use an existing bucket, specify it here:
  bucket: training-bucket
  csi.storage.k8s.io/provisioner-secret-name: minio-sec
  csi.storage.k8s.io/provisioner-secret-namespace: training
  csi.storage.k8s.io/controller-publish-secret-name: minio-sec
  csi.storage.k8s.io/controller-publish-secret-namespace: training
  csi.storage.k8s.io/node-stage-secret-name: minio-sec
  csi.storage.k8s.io/node-stage-secret-namespace: training
  csi.storage.k8s.io/node-publish-secret-name: minio-sec
  csi.storage.k8s.io/node-publish-secret-namespace: training