apiVersion: v1
kind: Pod
metadata:
  name: minio-test-pod
  namespace: training
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: storage
          mountPath: /storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: minio-pvc
