# kubectl taint nodes node1 prod=true:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  name: echo-server-pod
  namespace: training
  labels:
    app-name: "echo-server"
    env: "dev"
spec:
  tolerations:
    - key: prod
      value: "true"
      operator: Equal
  containers:
    - name: echo-server
      image: landrzejewski/echo-server:v2
      ports:
        - containerPort: 8080
          name: http
      resources:
        requests:
          memory: "64M"
          cpu: "250m"
        limits:
          memory: "128M"
          cpu: "500m"
      livenessProbe:
        httpGet:
          port: 8080
          path: /
        initialDelaySeconds: 30
        timeoutSeconds: 2
        periodSeconds: 3
        failureThreshold: 3
