apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cnpg-hostpath
  hostPath:
    path: "/tmp/pg"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cnpg-hostpath
  hostPath:
    path: "/tmp/pg"
