apiVersion: v1
kind: Service
metadata:
  name: pg-svc
  namespace: training
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: pg-cluster
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      name: pg