apiVersion: v1
kind: Service
metadata:
  name: echo-server-svc
  namespace: training
spec:
  selector:
    app-name: "echo-server"
  # clusterIP: 10.11.11.11
  # type: ClusterIP default
  ports:
    - port: 80
      targetPort: http #8080