apiVersion: batch/v1
kind: Job
metadata:
  namespace: training
  name: long-task-job
spec:
  completions: 3
  parallelism: 2
  ttlSecondsAfterFinished: 180
  activeDeadlineSeconds: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: long-task
          image: landrzejewski/long-task
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64M"
              cpu: "250m"

