apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: status-monitor-ds
  namespace: training
spec:
  selector:
#    matchLabels:
#      app-name: "status-monitor
    matchExpressions:
      - key: app-name
        values:
          - status-monitor
          - status
        operator: In
  template:
    metadata:
      namespace: training
      labels:
        app-name: "status-monitor"
        env: "dev"
    spec:
      containers:
        - name: status-monitor
          image: landrzejewski/status-monitor
          resources:
            requests:
              memory: "16M"
              cpu: "250m"