# nfs-server-deployment.yaml
# NFS server deployment with PV/PVC and demo usage pod

# sudo apt install nfs-common -y on each node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:12
          env:
            - name: SHARED_DIRECTORY
              value: "/exports"
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - name: nfs-storage
              mountPath: /exports
      volumes:
        - name: nfs-storage
          emptyDir: {}  # For testing; data disappears if pod restarts
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  clusterIP: None  # Headless service
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.training.svc.cluster.local
    path: /exports
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-client-demo
spec:
  containers:
    - name: demo
      image: busybox
      command: ["/bin/sh", "-c", "while true; do date >> /mnt/testfile.txt; sleep 5; done"]
      volumeMounts:
        - name: nfs-storage
          mountPath: /mnt
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
