apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: training
spec:
  resources:
    requests:
      storage: 5G
  accessModes:
    - ReadWriteOnce
  storageClassName: fast