apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater-dep
  namespace: training
  annotations:
    kubernetes.io/change-cause: "initial release"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: "updater"
  template:
    metadata:
      namespace: training
      labels:
        app-name: "updater"
    spec:
      containers:
        - name: nginx
          image: nginx:1.21-alpine
          ports:
            - containerPort: 80
          volumeMounts:
              - name: www
                mountPath: /usr/share/nginx/html
        - name: updater
#          image: landrzejewski/updater:v1
#          args:
#            - "20"

          image: landrzejewski/updater:v2
#          env:
#            - name: INTERVAL
#              value: "20"

#          env:
#            - name: INTERVAL
#              valueFrom:
#                configMapKeyRef:
#                  key: INTERVAL
#                  name: updater-cm

          envFrom:
            - configMapRef:
                name: updater-cm
          volumeMounts:
             - mountPath: /config
               name: config
             - mountPath: /storage
               name: storage
             - name: www
               mountPath: /var/htdocs

      volumes:
        - name: config
          configMap:
            name: updater-cm
        - name: storage
          persistentVolumeClaim:
            claimName: storage-pvc
        - name: www
          # emptyDir: {}
          emptyDir:
            medium: Memory
          #hostPath:
          #  path: /tmp/storage
