apiVersion: v1
kind: ConfigMap
metadata:
  namespace: training
  name: init-db-scripts-cm
data:
  create-tables.sql: "CREATE TABLE users(ID SERIAL PRIMARY KEY, name VARCHAR(30), email VARCHAR(30));"
---
apiVersion: v1
kind: Pod
metadata:
  namespace: training
  name: postgres-po
  labels:
    app-name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:17-alpine
      ports:
        - containerPort: 5432
          name: db
      env:
        - name: POSTGRES_DB
          value: training
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
      volumeMounts:
        - name: init-db-scripts
          mountPath: /docker-entrypoint-initdb.d
      resources:
        requests:
          memory: "128M"
          cpu: "250m"
        limits:
          memory: "512M"
          cpu: "500m"
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 30
        timeoutSeconds: 2
        periodSeconds: 3
        failureThreshold: 3
  volumes:
    - name: init-db-scripts
      configMap:
        name: init-db-scripts-cm
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: training
spec:
  selector:
    app-name: "postgres"
  ports:
    - port: 5432
      targetPort: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: training
  name: users-dep
  annotations:
    kubernetes.io/change-cause: "initial release"
spec:
  replicas: 3
  selector:
    matchLabels:
      app-name: users
  template:
    metadata:
      namespace: training
      labels:
        app-name: users
    spec:
      containers:
        - name: users
          image: landrzejewski/users:latest
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: 64M
              cpu: "250m"
            limits:
              memory: 128M
              cpu: "500m"




